### ISSUE TITLE
Wrong state

### ISSUE THREAD

**Issue by fmirault** [Scarygami/scary-giiker-cube#1]
Hi,

When I connect my shuffled Giiker, the initial state is not the same as my cube, I supposed there are maybe some mistakes with the algorithm that convert Giiker State Data to rendering colors ?

**Comment by fmirault** [comment]
I finally found that the original Supercube app has the same mistakes, it means that my cube has some forgotten moves, so it's not an algorithm problem :)

**Comment by Scarygami** [comment]
Yeah, I noticed as well, that the cube get's out-of-sync quite easily, especially with fast moves.
Only way to fix this is to solve the cube and then use the "Reset" functionality in either the Supercube app or my web app in settings.
